//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BinPackingHints) DeepCopyInto(out *BinPackingHints) {
	*out = *in
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BinPackingHints.
func (in *BinPackingHints) DeepCopy() *BinPackingHints {
	if in == nil {
		return nil
	}
	out := new(BinPackingHints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CPUStats) DeepCopyInto(out *CPUStats) {
	*out = *in
	if in.QuadrantSketches != nil {
		in, out := &in.QuadrantSketches, &out.QuadrantSketches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CPUStats.
func (in *CPUStats) DeepCopy() *CPUStats {
	if in == nil {
		return nil
	}
	out := new(CPUStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerOverride) DeepCopyInto(out *ContainerOverride) {
	*out = *in
	if in.MinCPU != nil {
		in, out := &in.MinCPU, &out.MinCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxCPU != nil {
		in, out := &in.MaxCPU, &out.MaxCPU
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MinMemory != nil {
		in, out := &in.MinMemory, &out.MinMemory
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.MaxMemory != nil {
		in, out := &in.MaxMemory, &out.MaxMemory
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerOverride.
func (in *ContainerOverride) DeepCopy() *ContainerOverride {
	if in == nil {
		return nil
	}
	out := new(ContainerOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerResourceStats) DeepCopyInto(out *ContainerResourceStats) {
	*out = *in
	in.CPU.DeepCopyInto(&out.CPU)
	in.Memory.DeepCopyInto(&out.Memory)
	if in.NodeSketches != nil {
		in, out := &in.NodeSketches, &out.NodeSketches
		*out = make([]NodeSketchEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastOOMKill != nil {
		in, out := &in.LastOOMKill, &out.LastOOMKill
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerResourceStats.
func (in *ContainerResourceStats) DeepCopy() *ContainerResourceStats {
	if in == nil {
		return nil
	}
	out := new(ContainerResourceStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemoryStats) DeepCopyInto(out *MemoryStats) {
	*out = *in
	if in.QuadrantSketches != nil {
		in, out := &in.QuadrantSketches, &out.QuadrantSketches
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastUpdated != nil {
		in, out := &in.LastUpdated, &out.LastUpdated
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MemoryStats.
func (in *MemoryStats) DeepCopy() *MemoryStats {
	if in == nil {
		return nil
	}
	out := new(MemoryStats)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeSketchEntry) DeepCopyInto(out *NodeSketchEntry) {
	*out = *in
	if in.LastSeen != nil {
		in, out := &in.LastSeen, &out.LastSeen
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeSketchEntry.
func (in *NodeSketchEntry) DeepCopy() *NodeSketchEntry {
	if in == nil {
		return nil
	}
	out := new(NodeSketchEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProfileContainerStatus) DeepCopyInto(out *ProfileContainerStatus) {
	*out = *in
	in.Stats.DeepCopyInto(&out.Stats)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProfileContainerStatus.
func (in *ProfileContainerStatus) DeepCopy() *ProfileContainerStatus {
	if in == nil {
		return nil
	}
	out := new(ProfileContainerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Recommendation) DeepCopyInto(out *Recommendation) {
	*out = *in
	out.CPURequest = in.CPURequest.DeepCopy()
	out.CPULimit = in.CPULimit.DeepCopy()
	out.MemoryRequest = in.MemoryRequest.DeepCopy()
	out.MemoryLimit = in.MemoryLimit.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Recommendation.
func (in *Recommendation) DeepCopy() *Recommendation {
	if in == nil {
		return nil
	}
	out := new(Recommendation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfile) DeepCopyInto(out *WorkloadProfile) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfile.
func (in *WorkloadProfile) DeepCopy() *WorkloadProfile {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfile)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProfile) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileList) DeepCopyInto(out *WorkloadProfileList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkloadProfile, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileList.
func (in *WorkloadProfileList) DeepCopy() *WorkloadProfileList {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkloadProfileList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileSpec) DeepCopyInto(out *WorkloadProfileSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ContainerOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CooldownMinutes != nil {
		in, out := &in.CooldownMinutes, &out.CooldownMinutes
		*out = new(int32)
		**out = **in
	}
	if in.CollectionIntervalSeconds != nil {
		in, out := &in.CollectionIntervalSeconds, &out.CollectionIntervalSeconds
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileSpec.
func (in *WorkloadProfileSpec) DeepCopy() *WorkloadProfileSpec {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadProfileStatus) DeepCopyInto(out *WorkloadProfileStatus) {
	*out = *in
	if in.Containers != nil {
		in, out := &in.Containers, &out.Containers
		*out = make([]ProfileContainerStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.MetricsRecommendations != nil {
		in, out := &in.MetricsRecommendations, &out.MetricsRecommendations
		*out = make([]Recommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Recommendations != nil {
		in, out := &in.Recommendations, &out.Recommendations
		*out = make([]Recommendation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastApplied != nil {
		in, out := &in.LastApplied, &out.LastApplied
		*out = (*in).DeepCopy()
	}
	if in.LastEvaluated != nil {
		in, out := &in.LastEvaluated, &out.LastEvaluated
		*out = (*in).DeepCopy()
	}
	if in.BinPacking != nil {
		in, out := &in.BinPacking, &out.BinPacking
		*out = new(BinPackingHints)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadProfileStatus.
func (in *WorkloadProfileStatus) DeepCopy() *WorkloadProfileStatus {
	if in == nil {
		return nil
	}
	out := new(WorkloadProfileStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkloadTargetRef) DeepCopyInto(out *WorkloadTargetRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkloadTargetRef.
func (in *WorkloadTargetRef) DeepCopy() *WorkloadTargetRef {
	if in == nil {
		return nil
	}
	out := new(WorkloadTargetRef)
	in.DeepCopyInto(out)
	return out
}
