---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - replicasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - clusterprofiles
  - namespaceprofiles
  - workloadprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - clusterprofiles/finalizers
  - namespaceprofiles/finalizers
  - workloadprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - clusterprofiles/status
  - namespaceprofiles/status
  - workloadprofiles/status
  verbs:
  - get
  - patch
  - update
