---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - workloadprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - workloadprofiles/finalizers
  verbs:
  - update
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - workloadprofiles/status
  verbs:
  - get
  - patch
  - update
