# This rule is not used by the project saturdai itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the autosize.saturdai.auto.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: saturdai
    app.kubernetes.io/managed-by: kustomize
  name: workloadprofile-editor-role
rules:
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - workloadprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autosize.saturdai.auto
  resources:
  - workloadprofiles/status
  verbs:
  - get
