apiVersion: autosize.saturdai.auto/v1
kind: WorkloadProfile
metadata:
  labels:
    app.kubernetes.io/name: saturdai
    app.kubernetes.io/managed-by: kustomize
  name: workloadprofile-sample
spec:
  targetRef:
    kind: Deployment
    name: workloadprofile-sample
  mode: balanced
  cooldownMinutes: 15
  collectionIntervalSeconds: 30
