apiVersion: apps/v1
kind: Deployment
metadata:
  name: workloadprofile-sample
  labels:
    app.kubernetes.io/name: saturdai
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workloadprofile-sample
  template:
    metadata:
      labels:
        app: workloadprofile-sample
    spec:
      containers:
        - name: app
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: workloadprofile-sample
  labels:
    app.kubernetes.io/name: saturdai
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app: workloadprofile-sample
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80